packages:
  - apps/*
  - packages/*
  - scripts/*
  - scripts
  - "!**/node_modules/**"
  - "!node_modules"

catalog:
  "@eslint/js": 9.34.0
  "@hono/node-server": 1.19.1
  "@supabase/supabase-js": 2.45.0
  "@types/node": 20.19.11
  arktype: 2.1.21
  dotenv: 17.2.2
  eslint: 9.34.0
  hono: 4.9.0
  jiti: 2.5.1
  prettier: 3.6.2
  stripe: 14.0.0
  tap: 21.1.0
  tsx: 4.20.5
  typescript: 5.9.2
  typescript-eslint: 8.42.0
  "@faremeter/fetch": 0.15.0
  "@faremeter/wallet-solana": 0.15.0
  "@faremeter/payment-solana": 0.15.0
  "@faremeter/types": 0.15.0
  "@solana/web3.js": 1.98.4
  "@solana/spl-token": 0.4.13
  bs58: 4.0.1
  resend: 3.0.0
  bcrypt: 5.1.1
  "@types/bcrypt": 5.0.2

catalogMode: prefer
linkWorkspacePackages: true
